### ISSUE TITLE
How to pick items?

### ISSUE THREAD

**Issue by bergel** [psvensson/golgotterath#1]
Would be great to have a list of command on how to pick items, how to fight...

**Comment by psvensson** [comment]
You are absolutely right! I will add commands to the README now. I have had in mind to create a help screen, but haven't had the time yet. Just a minute for the README, though..

**Comment by psvensson** [comment]
OK, I've now added some info the the README, I hope it is sufficient to get started.
https://github.com/psvensson/golgotterath/blob/master/README.md

**Comment by bergel** [comment]
help within the game, accessible from pressing `h` or `?` would be great
